name: Send Empty File to Slack

on:
  push:
    branches:
      - main

jobs:
  send_to_slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1.26

      - name: Create Empty File
        run: touch empty.txt

      - name: Send File to Slack
        uses: Ilshidur/action-slack@v3
        with:
          status: "Empty file sent!"
          file: empty.txt
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
