name: Send Empty File to Slack

on:
  push:
    branches:
      - main

jobs:
  send_to_slack:
    runs-on: ubuntu-latest

    steps:
      - name: Create Empty File
        run: touch empty.txt

      - name: Send Empty File to Slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          text: |
            Here is the empty file:
            ```
            $(cat empty.txt)
            ```
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
