name: Send Empty File to Slack

on:
  push:
    branches:
      - main

jobs:
  send_to_slack:
    runs-on: ubuntu-latest

    steps:
      - name: Create Empty File
        run: touch empty.txt

      - name: Send Empty File to Slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "Sending an empty file to Slack",
              "attachments": [
                {
                  "text": "Empty file",
                  "fallback": "Empty file",
                  "title": "Empty File",
                  "title_link": "https://github.com/${{ github.repository }}/blob/${{ github.sha }}/empty.txt"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
