name: Send Changelog to Slack

on:
  release:
    types:
      - created

jobs:
  send_to_slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate Changelog
        run: npx conventional-changelog -p angular -i changelog.md -s

      - name: Send Changelog to Slack
        uses: slackapi/slack-github-action@v3
        with:
          text: |
            New release published! Here is the changelog:
            ```
            $(cat changelog.md)
            ```
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
