name: List Files

on:
  push:
    branches:
      - main

jobs:
  list_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: List Files
        run: |
          find . -type f > file_list.txt
          cat file_list.txt
