name: Notify on Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install # or yarn install

      - name: Generate Changelog
        run: npx conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Read Changelog Content
        id: read_changelog
        run: echo "::set-output name=changelog_content::$(cat CHANGELOG.md)"

      - name: Send Changelog to Slack
        uses: act10ns/slack@v2
        with:
          status: "New release published! Here is the changelog:"
          text: ${{ steps.read_changelog.outputs.changelog_content }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
