name: Convert Markdown to JSON

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Extract Release Notes
        id: extract_release_notes
        run: |
          release_notes=$(cat CHANGELOG.md)
          echo "::set-output name=notes::${release_notes}"

      - name: Convert Markdown to JSON
        id: convert_md_to_json
        run: |
          markdown="${{ steps.extract_release_notes.outputs.notes }}"
          json=$(curl -X POST -H "Content-Type: text/markdown" --data-binary "$markdown" https://api.github.com/markdown/raw)
          echo "::set-output name=json::${json}"

      - name: Send JSON to Slack
        run: |
          json="${{ steps.convert_md_to_json.outputs.json }}"
          echo "Converted JSON: $json"
          # Send JSON to Slack using curl or another method
