name: Extract and Send Release Notes

on:
  release:
    types: [published]

jobs:
  extract_and_send_notes:
    name: Extract and Send Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Extract Release Notes
        id: extract_notes
        uses: CSchoel/release-notes-from-changelog@v1

      - name: Send Release Notes to Slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          text: "New Release Published!\nRelease Notes: ${steps.extract_notes.outputs.release_notes}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
