name: Send Release Notes to Slack

on:
  release:
    types:
      - created

jobs:
  send_to_slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Extract Release Notes
        id: extract_release_notes
        run: |
          release_notes=$(cat CHANGELOG.md)
          echo "::set-output name=notes::${release_notes}"

      - name: Convert Release Notes to Markdown
        id: convert_to_markdown
        uses: ma-ha/markdown-to-json-action@v1
        with:
          source: ${{ steps.extract_release_notes.outputs.notes }}
          target: release_notes.json
          useFrontmatter: false

      - name: Read Converted Release Notes
        id: read_converted_notes
        run: |
          release_notes=$(cat release_notes.json)
          echo "::set-output name=converted_notes::${release_notes}"

      - name: Send Release Notes to Slack
        run: |
          release_notes="${{ steps.read_converted_notes.outputs.converted_notes }}"
          echo "Release Notes: $release_notes"
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "New Release Notes:\n$release_notes"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
