name: Notify Slack on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  notify_slack:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          version: ${{ github.ref_name }}
          path: ./CHANGELOG.md

      - name: Send Release Notes to Slack
        uses: slackapi/slack-github-action@v1
        with:
          status: "New tag published! Here are the release notes for version ${{ github.ref_name }}:"
          text: ${{ steps.changelog_reader.outputs.changes }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
