name: Notify on Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install # or yarn install

      - name: Generate Changelog
        run: npx conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Send Changelog to Slack
        uses: ilshidur/action-slack@v2
        with:
          args: '{"text": "New release published! Here is the changelog:", "attachments": [{"color": "#36a64f", "text": "```' + '$(cat CHANGELOG.md)' + '```"}]}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
