name: Send Release Notes to Slack

on:
  push:
    branch: main

jobs:
  send_to_slack:
    name: Send Release Notes to Slack
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "amit@sutara.org"
          git config --global user.name "amitsinghsutara"

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run release-it
        run: npx release-it

      - name: Extract Release Notes
        id: extract_release_notes
        uses: ffurrer2/extract-release-notes@v2

      - name: Extract version number
        id: extract_version_number
        run: |
          version=$(awk '/^## \[[0-9]+\.[0-9]+\.[0-9]+\]/ {print substr($3, 2, length($3)-2); exit}' CHANGELOG.md)
          echo "::set-output name=version::$version"

      - name: Send to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*New Release Notes:*\nVersion: v${version}\n\n${{ steps.extract_release_notes.outputs.release_notes }}"
                }
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
