name: Send Release Notes to Slack

on:
  push:
    branch: main

jobs:
  send_to_slack:
    name: Send Release Notes to Slack
    runs-on: ubuntu-latest
    steps:


      - name: Set up Git
        run: |
          git config --global user.email "amit@sutara.org"
          git config --global user.name "amitsinghsutara"
          
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Install dependencies
        run: npm install

      # - name: Run release-it
      #   run: npx release-it
      - name: release-it
        run: npx release-it 

      - name: Extract version number
        id: extract_version_number
        run: |
          version=$(jq -r '.version' package.json)
          echo "::set-output name=version::$version"

      - name: Extract Release Notes
        id: extract_release_notes
        run: |
          awk -v ver="${{ steps.extract_version_number.outputs.version }}" '/^## Version / {
              if (p) { exit }
              if ($3 == ver) { p=1; next }
            }
            p && NF && !/^## Version / { print }
          ' CHANGELOG.md > release_notes.txt

      - name: Send to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "New Release Notes:\nVersion: v${{ steps.extract_version_number.outputs.version }}\n$(cat release_notes.txt)"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

