name: Send Release Notes to Slack

on:
  release:
    types: [published]

jobs:
  send_to_slack:
    name: Send Release Notes to Slack
    runs-on: ubuntu-latest
    steps:

      # - name: Set up Git
      #   run: |
      #     git config --global user.email "amit@sutara.org"
      #     git config --global user.name "amitsinghsutara"
          
      - name: Checkout Code
        uses: actions/checkout@v2

      # - name: Install jq
      #   run: sudo apt-get install jq

      # - name: Install dependencies
      #   run: npm install

      # - name: Run release-it
      #   run: npx release-it
      - name: release-it
        uses: TheRealWaldo/release-it@v0.7.2
        with:
          json-opts: '{"dry-run": true}'
          
      - name: Extract Release Notes
        id: extract_release_notes
        uses: ffurrer2/extract-release-notes@v2

      - name: Extract version number
        id: extract_version_number
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"
          else
            echo "::set-output name=version::${GITHUB_REF#refs/heads/chore: release v}"
          fi
      - name: Send to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "New Release Notes:\nVersion: ${{ steps.extract_version_number.outputs.version }}\n${{ steps.extract_release_notes.outputs.release_notes }}"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

