name: Send Release Notes to Slack

on:
  release:
    types:
      - created

jobs:
  send_to_slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Extract Release Notes
        id: extract_release_notes
        run: |
          release_notes=$(cat CHANGELOG.md)
          echo "::set-output name=notes::${release_notes}"

      - name: Convert Markdown to Text
        id: convert_to_text
        run: |
          release_notes="${{ steps.extract_release_notes.outputs.notes }}"
          echo "${release_notes}" | pandoc -f markdown -t plain -o release_notes.txt

      - name: Send Release Notes to Slack
        run: |
          release_notes=$(cat release_notes.txt)
          echo "Release Notes: $release_notes"
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "New Release Notes:\n$release_notes"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
