name: Send Changelog to Slack

on:
  release:
    types:
      - created

jobs:
  send_to_slack:
    runs-on: ubuntu-latest

    steps:

      - name: List Files in Workspace
        run: ls -la
        working-directory: ${{ github.workspace }}


      - name: Read CHANGELOG.md file
        id: read_changelog
        run: |
          changelog=$(cat './CHANGELOG.md')
          echo "::set-output name=changelog::$changelog"
        working-directory: ${{ github.workspace }}

      - name: Send Changelog to Slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "New release published! Here is the changelog:",
              "attachments": [
                {
                  "text": "${{ steps.read_changelog.outputs.changelog }}"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
