name: Notify on Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate Changelog
        run: npx conventional-changelog -p angular -i changelog.md -s

      - name: Create Release Notes Text File
        run: cat changelog.md > release_notes.txt

      - name: Send Release Notes to Slack
        uses: ilshidur/action-slack@v3
        with:
          status: "New release published! Here are the release notes:"
          text: |
            $(cat release_notes.txt)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
